// Server-only: real download links for paid digital art, kept OUT of
// lib/products.js on purpose. app/page.js is a client component that
// imports the PRODUCTS array directly, so anything in that file -- even
// fields the UI never displays -- gets bundled into the JavaScript sent
// to every visitor's browser. If the real TIFF links lived there, anyone
// could open dev tools and grab every full-res file for free, no purchase
// needed.
//
// This file is only ever imported from app/api/confirm/route.js, which
// runs on the server and only hands a link back after Stripe confirms the
// payment actually succeeded. Never import this from any "use client"
// file (app/page.js or anything it imports).
//
// Generated by scripts/upload-tiffs.mjs -- re-run that script if you need
// to re-upload or add more art.

export const PRODUCT_FILES = {
  "609-door": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/609-door-acb9c8b4b1ac58a3.tif",
  "abra-flower-hat": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/abra-flower-hat-d75487b04aa10647.tif",
  "back-to-new-orleans": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/back-to-new-orleans-22c418b0d04d14a6.tif",
  "banana": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/banana-6a87b9c791ebf71d.tif",
  "band": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/band-81c09bd90cff5f18.tif",
  "bass-pro-shop": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/bass-pro-shop-26c1448e98c139d2.tif",
  "blue-fence": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/blue-fence-f1d1e56bcd5af20d.tif",
  "bouquet": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/bouquet-3d7d038872342344.tif",
  "cafe-du-monde": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/cafe-du-monde-dddfab8c7744ed62.tif",
  "celestial-waving-flower": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/celestial-waving-flower-d04a1f9bf947ea36.tif",
  "chickens": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/chickens-9a91c6ba2b31ad86.tif",
  "cold-december-morning": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/cold-december-morning-4f204b8491d80114.tif",
  "converse-and-wildflowers": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/converse-and-wildflowers-b6e12674eb1ea0c3.tif",
  "crow-in-flight": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/crow-in-flight-3d38a563d9689b50.tif",
  "door-on-tchoup": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/door-on-tchoup-d4043a3db28d523f.tif",
  "drum-green": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/drum-green-bf2516e25cdef747.tif",
  "earth-swallows-car": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/earth-swallows-car-4a159429a39457db.tif",
  "fairy-flower": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/fairy-flower-1a09b1c0c08e67be.tif",
  "flower-in-front-of-door": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/flower-in-front-of-door-0351571d8a63339d.tif",
  "flower-jar": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/flower-jar-cd6dba959fca7209.tif",
  "flower-lanterns": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/flower-lanterns-f6cffa6fd87e64f0.tif",
  "flower-on-fence": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/flower-on-fence-a2d323cd9978ac09.tif",
  "flowers-by-the-tracks": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/flowers-by-the-tracks-db968771174b0caa.tif",
  "flowers-in-fence": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/flowers-in-fence-d07f1843180efe23.tif",
  "franklin-cross": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/franklin-cross-14cc6175ca8ea94f.tif",
  "frenchmen": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/frenchmen-bf8fc1763bb72780.tif",
  "gardener-hands": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/gardener-hands-da0131929c8c8bb7.tif",
  "glorias": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/glorias-ae8b6ce4e3dff760.tif",
  "gods-light": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/gods-light-63ea6c3ceb72b57c.tif",
  "green-leaves": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/green-leaves-19725c478cdc3381.tif",
  "hands-holding-flowers": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/hands-holding-flowers-44e925fc3640ab9b.tif",
  "her-curves": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/her-curves-d260528a5d87a41f.tif",
  "house-on-esplanade": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/house-on-esplanade-44ac039c94f14fce.tif",
  "house-to-marigny": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/house-to-marigny-d8fe064b7d773ade.tif",
  "if-im-still-breathing": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/if-im-still-breathing-eaab0c0b38511b47.tif",
  "jeannette-cutting-flowers": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/jeannette-cutting-flowers-9a22f79659a1349f.tif",
  "jeannette-reading": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/jeannette-reading-2fe33af13ef5310a.tif",
  "jeannette-ribbon": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/jeannette-ribbon-40abfb8673a944de.tif",
  "jeannettes-hands": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/jeannettes-hands-f3f576d248e2d3a5.tif",
  "jeannettes-rose": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/jeannettes-rose-3b6370dc9a549196.tif",
  "little-mermaid-flower": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/little-mermaid-flower-b4dbfe4d83af8b21.tif",
  "lush": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/lush-b5be9d77f514761a.tif",
  "magnolia-in-the-city": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/magnolia-in-the-city-557ad3b15359a770.tif",
  "my-favorite-flower": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/my-favorite-flower-0fd9af5aa694539c.tif",
  "new-orleans-night": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/new-orleans-night-023df5e1a8656401.tif",
  "nightwork": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/nightwork-abe913785d5f8436.tif",
  "n-rampart": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/n-rampart-2a19c2210119ccdd.tif",
  "orange-flower": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/orange-flower-543bbd88b17067fc.tif",
  "orange-flower-leonidas": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/orange-flower-leonidas-5c116f2e35dad01c.tif",
  "orange-fruit": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/orange-fruit-967c1af2b083726f.tif",
  "palm-before-storm": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/palm-before-storm-4e2b348323763bc9.tif",
  "pink-palm": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/pink-palm-080db8510f120d7c.tif",
  "pink-rose": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/pink-rose-f2dba26ebe581f4b.tif",
  "porch-drapes": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/porch-drapes-a5c7b15e5ce1cb53.tif",
  "porch-light": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/porch-light-6d4f93be9b1c383a.tif",
  "red-car": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/red-car-6b46da3bfc36d270.tif",
  "red-roses": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/red-roses-4fe059c227b608f7.tif",
  "rose-garden": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/rose-garden-f6a159a86074ce75.tif",
  "rose-in-hand": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/rose-in-hand-2b33a0a6fbc6b931.tif",
  "rose-on-building": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/rose-on-building-f7df586c26581072.tif",
  "roses": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/roses-04e64690a58bebc2.tif",
  "screens": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/screens-e909e4a2649ee4cc.tif",
  "shine-bright": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/shine-bright-6a7b15a98ce7fc33.tif",
  "sunflower-high": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/sunflower-high-08d690d39cc82f9e.tif",
  "sunflower-white-house": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/sunflower-white-house-e806081f51663768.tif",
  "sunrise": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/sunrise-993c10d3bb2d44bb.tif",
  "swamp-trees": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/swamp-trees-8326a79fb2d651b1.tif",
  "tassles": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/tassles-b5172726bf6733cf.tif",
  "teardrop-on-leaf": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/teardrop-on-leaf-d58d422ad49ea713.tif",
  "thread-of-fate": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/thread-of-fate-e8faae4ba00052b2.tif",
  "too-close-to-the-sun": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/too-close-to-the-sun-1f8e0e11bc38b61e.tif",
  "tower-palm": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/tower-palm-8636f99458ee89e4.tif",
  "tree-magic": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/tree-magic-1b5fc045bd9edd7c.tif",
  "two-flowers": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/two-flowers-28307b2599a60ada.tif",
  "wires": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/wires-d13b1745351419e5.tif",
  "yellow-and-blue": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/yellow-and-blue-dc94200187eb5ed7.tif",
  "yellow-on-blue": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/yellow-on-blue-758e30da962e658b.tif",
  "yoni-flowers": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/yoni-flowers-55ea1040d776135e.tif",
  "you-are-safe-with-me": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/you-are-safe-with-me-c1a1688400de7e5d.tif",
  "clasping-flower": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/clasping-flower-1713842874aeda60.tif",
  "flowers-and-roof": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/flowers-and-roof-4e83931077cf9bf0.tif",
  "french-quarter-door": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/french-quarter-door-02f34fe726be5590.tif",
  "fuchsia": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/fuchsia-9b73ef7417b4f088.tif",
  "green-plant-blue-house": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/green-plant-blue-house-a551298d1da788cf.tif",
  "holy-flowers": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/holy-flowers-0a5bcfe00273ed3d.tif",
  "in-dreams": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/in-dreams-8e9647da36899426.tif",
  "white-and-blue": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/white-and-blue-5f6f2ce307bcd44d.tif",
  "wildflower": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/wildflower-74d4001703d0133b.tif",
  "yellow-flower": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/yellow-flower-7a99c6c58ac7e887.tif",
  "yellow-flowers": "https://pub-a295f7f7ba3f4176b9210c3055938325.r2.dev/tiffs/yellow-flowers-3be9b2f2b247ffbb.tif",
};

export function getFileUrl(id) {
  return PRODUCT_FILES[id];
}
