// Server-only: real download links for paid digital art, kept OUT of
// lib/products.js on purpose. app/page.js is a client component that
// imports the PRODUCTS array directly, so anything in that file -- even
// fields the UI never displays -- gets bundled into the JavaScript sent
// to every visitor's browser. If the real TIFF links lived there, anyone
// could open dev tools and grab every full-res file for free, no purchase
// needed.
//
// This file is only ever imported from app/api/confirm/route.js, which
// runs on the server and only hands a link back after Stripe confirms the
// payment actually succeeded. Never import this from any "use client"
// file (app/page.js or anything it imports).
//
// Generated by scripts/upload-tiffs.mjs -- re-run that script if you need
// to re-upload or add more art.

export const PRODUCT_FILES = {
  "609-door": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/609-door-WL0fppO0u96EqEoRXlULGtGvDywE0T.tif",
  "abra-flower-hat": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/abra-flower-hat-mrcAI103IzpKk1OKFYOVsWzaSfKty3.tif",
  "back-to-new-orleans": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/back-to-new-orleans-FJKEKPHbWEycMhAL1Qpwi3lELnujSu.tif",
  "banana": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/banana-F6QS7RiQP3zht5vn6kG5SxaN8sjvGy.tif",
  "band": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/band-PSSF5KlfsjNVgRDCdLmHncTtIxBO1V.tif",
  "bass-pro-shop": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/bass-pro-shop-PRquTMmeYmTxZkyD8kNKyLAkYc396c.tif",
  "blue-fence": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/blue-fence-4M5rDtvUMfzTxtDY9kNOyVd57a6T2l.tif",
  "bouquet": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/bouquet-XWNX3fqf3pbILqDntaFNwgPCfnHwFK.tif",
  "cafe-du-monde": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/cafe-du-monde-89KB1qGvPINFBeS7CHx933RQGyYd8S.tif",
  "celestial-waving-flower": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/celestial-waving-flower-gZR4PIcZk3AzU2sLUzNHPmA6jwZuoY.tif",
  "chickens": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/chickens-z2XSDSH091S95ZLDkFoReGeRE9iusC.tif",
  "cold-december-morning": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/cold-december-morning-IHJGMaI4JZ5mS3Hux61iMxcfKVl0aX.tif",
  "converse-and-wildflowers": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/converse-and-wildflowers-V51Q9afLTCYIZl8J1znrejTQJWBlla.tif",
  "crow-in-flight": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/crow-in-flight-ZRn3Jjg5eDMpbP9FVHipNQqpXnFy1Q.tif",
  "door-on-tchoup": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/door-on-tchoup-82JnpaMuSHml8s164jGDmB6h6paDLK.tif",
  "drum-green": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/drum-green-oLEwAPM7AznEAq42hTLAGff3ArWYyS.tif",
  "earth-swallows-car": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/earth-swallows-car-t2dpCoByuZ03JVPydR7idjTQK8HJFg.tif",
  "fairy-flower": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/fairy-flower-GNQs020lXDDgNV5KhiXLui87yOcI31.tif",
  "flower-in-front-of-door": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/flower-in-front-of-door-5sNORqiJ6Ai1OATBbehj2sbGSuksly.tif",
  "flower-jar": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/flower-jar-81rSXnPhKov5szSBACPa4ZC32xISE6.tif",
  "flower-lanterns": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/flower-lanterns-KwRUL5dqQHqMew5HRZUs4bEVw7KkSA.tif",
  "flower-on-fence": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/flower-on-fence-kQlN6QcOn10MkxyP3oquMvNSC6dd3N.tif",
  "flowers-by-the-tracks": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/flowers-by-the-tracks-XYjrLN8249MgTn1ZOxOGRfMpa6yKru.tif",
  "flowers-in-fence": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/flowers-in-fence-q4J5y9ZZ0KMKPSYE51VivgSpc9k3OI.tif",
  "franklin-cross": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/franklin-cross-SqRCyUoQ4lkjRE0An0SySbGjYxhO0s.tif",
  "frenchmen": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/frenchmen-NFndj5e7EU1x6Q1SI7aHkbgUBGVvm0.tif",
  "gardener-hands": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/gardener-hands-QGIPcX511qRubuR5G3x3pWnVkP9cza.tif",
  "glorias": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/glorias-CirciXFZw8xV0ubu6C5TTGADUnUgKz.tif",
  "gods-light": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/gods-light-easBpJApKl8hm313HpVzKmnPMTZkXG.tif",
  "green-leaves": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/green-leaves-ZhHeGK0YgAQAywEW3UGjS2tnHBaP3c.tif",
  "hands-holding-flowers": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/hands-holding-flowers-y2cwHffZ8YCSNnVfFh70zO8BPtAb4X.tif",
  "her-curves": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/her-curves-L37d4TGefZZdq0vPUAtB6TqGm6BSSy.tif",
  "house-on-esplanade": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/house-on-esplanade-jk6kxhWYNA3bEFJgCRpzDPJRzcGVt9.tif",
  "house-to-marigny": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/house-to-marigny-LvSn9UxklyWQ2MAFP5PatnRPzX2930.tif",
  "if-im-still-breathing": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/if-im-still-breathing-adB6s09gwSpwAcOleUt6mnZ9eaMzVd.tif",
  "jeannette-cutting-flowers": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/jeannette-cutting-flowers-ThCI6gj6709jTh7uwGXE4qbjmro5vl.tif",
  "jeannette-reading": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/jeannette-reading-9tvgrDee16z3uOpSrIwyOEjfzjAOjX.tif",
  "jeannette-ribbon": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/jeannette-ribbon-vApFTk6WVjyzOG6KZgn2aKOSUZo3hi.tif",
  "jeannettes-hands": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/jeannettes-hands-ZcTz5MfjB9Yk7QiG6P3Lh3AmuDq7vv.tif",
  "jeannettes-rose": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/jeannettes-rose-rEmhi14moHGthHVgEErwbXsylFDr5S.tif",
  "little-mermaid-flower": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/little-mermaid-flower-eGQunYHoUirQVck6BtcGLKa5hP4xp3.tif",
  "lush": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/lush-nizpBGmU6q2aSSi6vOhAOnOCWzxFf0.tif",
  "magnolia-in-the-city": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/magnolia-in-the-city-38Di0LurcYH2d19O2z18fAV0jyXFfq.tif",
  "my-favorite-flower": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/my-favorite-flower-2GYk8gmJpFsXfiYDsKzzu2hV6HHknG.tif",
  "new-orleans-night": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/new-orleans-night-T5PAYknMen2MI1R3N6skRdud7UutKR.tif",
  "nightwork": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/nightwork-S2bfbs4vAs601nOMOkE7Seppby4puK.tif",
  "n-rampart": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/n-rampart-SDkQyn6QruL5rZMb3OXiNwL0WPhXeB.tif",
  "orange-flower": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/orange-flower-0IzDYnr9R5CqYw4ypT662SwkHhnCqh.tif",
  "orange-flower-leonidas": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/orange-flower-leonidas-ifGGXRFofV2HP28ijGfJw3SuLaWeMc.tif",
  "orange-fruit": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/orange-fruit-mc9b56E1Ell495Uu9523jMYftADEYi.tif",
  "palm-before-storm": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/palm-before-storm-Ejg1SiWaTQqmkiS2irvssg0CStEpXa.tif",
  "pink-palm": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/pink-palm-6Dz5VW01Bt047P4ox490GjFw8cPENb.tif",
  "pink-rose": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/pink-rose-AfH56zlDRnsEyWDNYmyfbTjSGMBLpw.tif",
  "porch-drapes": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/porch-drapes-t46SjtrtUieowDWJ1Ftn79BSmXNlEY.tif",
  "porch-light": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/porch-light-KFYDnidCv99OMVPu9j9pqHmlXtU4Qv.tif",
  "red-car": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/red-car-2FybkVj1U2gRou7FJ0z0EQsPocrvEB.tif",
  "red-roses": "https://uwbhsbyr92n0uf2i.public.blob.vercel-storage.com/tiffs/red-roses-ZSpytCkK24D45NBGX9NkL6NBphBdEM.tif",
  "rose-garden": "PENDING_TIFF_UPLOAD",
  "rose-in-hand": "PENDING_TIFF_UPLOAD",
  "rose-on-building": "PENDING_TIFF_UPLOAD",
  "roses": "PENDING_TIFF_UPLOAD",
  "screens": "PENDING_TIFF_UPLOAD",
  "shine-bright": "PENDING_TIFF_UPLOAD",
  "sunflower-high": "PENDING_TIFF_UPLOAD",
  "sunflower-white-house": "PENDING_TIFF_UPLOAD",
  "sunrise": "PENDING_TIFF_UPLOAD",
  "swamp-trees": "PENDING_TIFF_UPLOAD",
  "tassles": "PENDING_TIFF_UPLOAD",
  "teardrop-on-leaf": "PENDING_TIFF_UPLOAD",
  "thread-of-fate": "PENDING_TIFF_UPLOAD",
  "too-close-to-the-sun": "PENDING_TIFF_UPLOAD",
  "tower-palm": "PENDING_TIFF_UPLOAD",
  "tree-magic": "PENDING_TIFF_UPLOAD",
  "two-flowers": "PENDING_TIFF_UPLOAD",
  "wires": "PENDING_TIFF_UPLOAD",
  "yellow-and-blue": "PENDING_TIFF_UPLOAD",
  "yellow-on-blue": "PENDING_TIFF_UPLOAD",
  "yoni-flowers": "PENDING_TIFF_UPLOAD",
  "you-are-safe-with-me": "PENDING_TIFF_UPLOAD",
  "clasping-flower": "PENDING_TIFF_UPLOAD",
  "flowers-and-roof": "PENDING_TIFF_UPLOAD",
  "french-quarter-door": "PENDING_TIFF_UPLOAD",
  "fuchsia": "PENDING_TIFF_UPLOAD",
  "green-plant-blue-house": "PENDING_TIFF_UPLOAD",
  "holy-flowers": "PENDING_TIFF_UPLOAD",
  "in-dreams": "PENDING_TIFF_UPLOAD",
  "white-and-blue": "PENDING_TIFF_UPLOAD",
  "wildflower": "PENDING_TIFF_UPLOAD",
  "yellow-flower": "PENDING_TIFF_UPLOAD",
  "yellow-flowers": "PENDING_TIFF_UPLOAD",
};

export function getFileUrl(id) {
  return PRODUCT_FILES[id];
}
